---
#
# Ansible managed
#
repository:
  description: Check xz vulnerability (cve_2024_3094) on your system.
  homepage: https://buluma.github.io/
  topics: cve20243094, linux, security, system, ansible, molecule, playbook
